# Generated by Django 4.2.2 on 2023-06-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickpayapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
