# Generated by Django 4.2.2 on 2023-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickpayapi', '0002_child_is_parent_parent_is_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='child_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='parent_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='child',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='parent',
            name='monthly_budget',
            field=models.IntegerField(default=0),
        ),
    ]
