# Generated by Django 4.2.2 on 2023-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickpayapi', '0003_rename_child_user_child_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='financial_goal',
            field=models.IntegerField(default=3),
        ),
    ]
